# Generated by Django 3.2.4 on 2021-06-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/profile_pics/default.png', upload_to='media/static/profile_pics'),
        ),
    ]
