# Generated by Django 3.2.4 on 2021-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_bodyweight'),
        ('users', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.ManyToManyField(to='tracker.BodyWeight'),
        ),
    ]
