# Generated by Django 3.2.4 on 2021-06-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_bodyweight_weight'),
        ('users', '0007_auto_20210619_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.bodyweight'),
            preserve_default=False,
        ),
    ]
