# Generated by Django 3.2.4 on 2021-06-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210619_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='weight',
        ),
    ]
