# Generated by Django 3.2.4 on 2021-06-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_bodyweight_profile'),
        ('users', '0009_remove_profile_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=15, null=True)),
                ('title', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.ManyToManyField(related_name='user_weight', to='tracker.BodyWeight'),
        ),
    ]
