# Generated by Django 3.2.4 on 2021-06-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_routine_description'),
        ('users', '0012_alter_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.ManyToManyField(to='tracker.BodyWeight'),
        ),
    ]
