# Generated by Django 3.2.4 on 2021-06-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_bodyweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyweight',
            name='weight',
            field=models.FloatField(max_length=4, null=True),
        ),
    ]
