# Generated by Django 3.2.4 on 2021-06-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_weight'),
        ('tracker', '0004_alter_bodyweight_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodyweight',
            name='user',
        ),
        migrations.AddField(
            model_name='bodyweight',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
    ]
