# Generated by Django 3.2.4 on 2021-06-20 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_weight'),
        ('tracker', '0005_auto_20210619_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyweight',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='bodyweight', to='users.profile'),
        ),
    ]
