# Generated by Django 3.2.4 on 2021-06-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_bodyweight_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('set1', models.IntegerField()),
                ('set2', models.IntegerField()),
                ('set3', models.IntegerField()),
                ('rep_set1', models.IntegerField()),
                ('rep_set2', models.IntegerField()),
                ('rep_set3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(max_length=4, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bodyweight',
            name='profile',
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workouts', models.ManyToManyField(to='tracker.Excercise')),
            ],
        ),
        migrations.AddField(
            model_name='excercise',
            name='weight',
            field=models.ManyToManyField(to='tracker.WorkoutWeight'),
        ),
    ]
