# Generated by Django 3.2.4 on 2021-06-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_bodyweight_human'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='goal',
        ),
    ]
