# Generated by Django 3.2.4 on 2021-06-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_workout_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercise',
            name='set1',
        ),
        migrations.RemoveField(
            model_name='excercise',
            name='set2',
        ),
        migrations.RemoveField(
            model_name='excercise',
            name='set3',
        ),
        migrations.AddField(
            model_name='excercise',
            name='filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='workouts',
            field=models.ManyToManyField(to='tracker.Excercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/static/workout_images'),
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
