# Generated by Django 3.2.4 on 2021-06-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20210630_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workouts',
            new_name='excercise',
        ),
        migrations.AlterField(
            model_name='excercise',
            name='rep_set1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='excercise',
            name='rep_set2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='excercise',
            name='rep_set3',
            field=models.IntegerField(default=0),
        ),
    ]
