# Generated by Django 3.2.4 on 2021-06-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20210630_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercise',
            name='filled',
        ),
        migrations.RemoveField(
            model_name='excercise',
            name='rep_set1',
        ),
        migrations.RemoveField(
            model_name='excercise',
            name='rep_set2',
        ),
        migrations.RemoveField(
            model_name='excercise',
            name='rep_set3',
        ),
        migrations.RemoveField(
            model_name='excercise',
            name='weight',
        ),
        migrations.AlterField(
            model_name='excercise',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Workout_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_set1', models.IntegerField(default=0)),
                ('rep_set2', models.IntegerField(default=0)),
                ('rep_set3', models.IntegerField(default=0)),
                ('filled', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.excercise')),
                ('weight', models.ManyToManyField(to='tracker.WorkoutWeight')),
            ],
        ),
    ]
